# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# cd into Development
function cdd {
      cd ~/Development
      if [ -e "$1" ]
      then
              cd $1
      fi

}
compdef '_files -W "$HOME/Development"' cdd


function tableflip {
  echo "（╯°□°）╯ ┻━┻";
}

function dxdd {
  if pgrep Xcode >/dev/null; then
    echo "Cannot delete derived data while Xcode is running!"
  else
    echo "Deleting `cd ~/Library/Developer/Xcode; pwd`/DerivedData"
    rm -rf ~/Library/Developer/Xcode/DerivedData
  fi
}

alias be='bundle exec'
alias home="vcsh dotfiles"

# run z script
. ~/bin/z.sh

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
